# Workflow name
name: 'Publish Storybook to S3'

# Event for the workflow
on:
  push:
    branches:
      - main

# List of jobs
jobs:
  s3-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 22.15.0
      - name: Install dependencies
        run: yarn
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy storybook to s3
        run: |
          OUT_DIR="out$RANDOM"
          echo "📦 Building Storybook to $OUT_DIR..."
          npm run build-storybook -- -o "$OUT_DIR"
          echo "☁️ Syncing to S3..."
          aws s3 sync "$OUT_DIR" s3://saguaro-storybook
          echo "✅ Done. Storybook deployed from $OUT_DIR"
        env:
          NODE_OPTIONS: --max-old-space-size=7680
